apiVersion: v1
kind: Service
metadata:
  name: nginx-ingress-service
  namespace: ingress
spec:
  selector:
    app.kubernetes.io/name: ingress-nginx
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
